normalize path if it is a case insensitive file system
python-poetry/poetry pull request #2421
Opened 2020-05-14 16:57 UTC by 0xF4D3C0D3

closes #2419(Virtualenv not always found in case insensitive filesystem)
the util func for checking whether it is a case sentive
or not is from [Steve Cohen](https://stackoverflow.com/a/36580834/7899226)

# Pull Request Check List
Resolves: #2419
- [x] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

I have no idea where to edit for documentation that I made the default behavior of `EnvManager.generate_env_name` normalize case of cwd. If needed, please let me know where to edit thank you.

2020-05-14 17:53 UTC, 0xF4D3C0D3 commented
I think this is unnecessary. I'm waiting for the original issuer's feedback.

2021-08-02 13:19 UTC, radoering requested changes
Imho, the change is reasonable. I couldn't find any documentation on the naming either. Maybe, there should be a changelog entry that says that the naming of virtualenv folders for Windows users will change. Thus, an existing virtualenv is not used anymore after updating poetry but a new one is created.

At least, the test needs some approvement. See comment on concerning lines.

2021-08-02 13:19 UTC, radoering commented on tests/utils/test_env.py
> +            assert venv_with_lowercase != venv_with_uppercase != venv_with_bothcase
I think, in its current state, the test does not do what it is supposed to do (even if the approach is fine). The test only checks if different pathes result in different venv names. (The pathes are different even if case is ignored!) The test should at least check two pathes that are equal for case insensitive file systems but different for case sensitive file systems.

Further, there are two minor quirks:
1. The assert will be true even if venv_with_lowercase and venv_with_bothcase are equal, e.g.
   ```
   >>> 'a' != 'b' != 'a'
   True
   ```
   Probably, there should be three asserts each comparing a pair of venv names.

2. The name of the test seems a little bit ambiguous to me (the meaning is "test: case should ...", but reads "'test case' should ...") and probably the wrong way around (case should be ignored for case insensitive file systems and not for case sensitive file systems).

All in all, my proposal for improvement:

```suggestion
def test_generate_env_name_ignores_case_for_case_insensitive_fs(tmp_dir):
    path_with_lowercase = Path(tmp_dir) / "cwd"
    path_with_uppercase = Path(tmp_dir) / "CWD"
    path_with_bothcase = Path(tmp_dir) / "CwD"

    venv_with_lowercase = EnvManager.generate_env_name(
        "simple-project", str(path_with_lowercase)
    )
    venv_with_uppercase = EnvManager.generate_env_name(
        "simple-project", str(path_with_uppercase)
    )
    venv_with_bothcase = EnvManager.generate_env_name(
        "simple-project", str(path_with_bothcase)
    )

    with tempfile.NamedTemporaryFile(prefix="TmP") as tmp_file:
        is_case_insensitive_fs = os.path.exists(tmp_file.name.lower())

    if is_case_insensitive_fs:
        assert venv_with_lowercase == venv_with_uppercase
        assert venv_with_lowercase == venv_with_bothcase
        assert venv_with_uppercase == venv_with_bothcase
    else:
        assert venv_with_lowercase != venv_with_uppercase
        assert venv_with_lowercase != venv_with_bothcase
        assert venv_with_uppercase != venv_with_bothcase
```

2021-11-21 17:19 UTC, radoering commented
@0xF4D3C0D3: May you consider to incorporate my requested changes and rebase your branch? Otherwise, if you don't mind I would like to create a new PR to make another try at getting this fix merged.

2021-11-22 16:23 UTC, 0xF4D3C0D3 commented
@radoering thanks for your contribution and feedback. However I think I couldn't do what you want soon. it seems to be better to close this issue and open new PR. Good luck!

2021-11-22 16:23 UTC, closed without merging