layout: make original toml content optional
python-poetry/poetry pull request #3008
Opened 2020-09-30 21:45 UTC by abn

This fixes a bug introduced via #2448.

2020-09-30 21:52 UTC, sdispater submitted a review, later dismissed

2020-10-01 04:23 UTC, finswimmer requested changes
Are the changes in `configuration.md`, `poetry.lock` and `pyproject.toml` intended to be in this PR?

Otherwise looks good :+1:

2020-10-01 06:35 UTC, abn commented
Yes. They are separated by commits. :)

2020-10-01 07:22 UTC, finswimmer approved these changes

2020-10-01 07:22 UTC, merged