Document the CLI action 'cache clear'
python-poetry/poetry pull request #3066
Opened 2020-10-03 14:08 UTC by peldszus

# Pull Request Check List

Resolves: #3065 

- [x] Added **tests** for changed code.
- [x] Updated **documentation** for changed code.

I trivially ticked the boxes: No code was added, but documentation.

2020-10-03 22:14 UTC, abn requested changes

2020-10-03 22:14 UTC, abn commented on docs/docs/cli.md
> +To clear the whole cache of packages from the `pypi` repository, run:
```suggestion
For example, to clear the whole cache of packages from the `pypi` repository, run:
```

2020-10-04 14:05 UTC, abn approved these changes

2020-10-04 14:06 UTC, merged

2021-06-07 15:23 UTC, peldszus commented
Hi @abn, since this documentation fix was already merged last Oct, I'm wondering when it will be reflected in [the rendered docs on the homepage](https://python-poetry.org/docs/cli/#cache) or put into a release. Is there the plan to make it visible there?