Updates in Basic Usage Doku for further specification on project and module names
python-poetry/poetry pull request #3257
Opened 2020-10-20 18:08 UTC by HallerPatrick

Following documentation changes should suffice to at least know that `tool.poetry.name` can be resolved as
module name and for other cases the `/doc/pyproject#packages` page is referenced.

Resolves: #2252

2020-10-28 13:56 UTC, stephsamson requested changes
Just a small typo :)

2020-10-28 13:56 UTC, stephsamson commented on docs/docs/basic-usage.md
> +Make sure that `tool.peotry.name` matches the module name or otherwise specified within
```suggestion
Make sure that `tool.poetry.name` matches the module name or otherwise specified within
```

2020-10-28 13:56 UTC, stephsamson commented on docs/docs/basic-usage.md
> +`tool.peotry.packages`.
```suggestion
`tool.poetry.packages`.
```

2020-12-31 08:25 UTC, TBBle commented
I just bounced off exactly this problem, and eventually found this pending PR (via #2252) documenting exactly what I was doing wrong (`tool.poetry.name` wasn't the package name, and there was no prompt that this resulted in no packages being installed, just the listed dependencies).

That said, this text is maybe a little unclear, as it suggests that 
> `tool.poetry.name` [is] specified within `tool.poetry.packages`

which is not the problem.

So perhaps
> Poetry assumes your package contains a packge with the same name as `tool.poetry.name`. If this is not the case, populate `tool.poetry.packages` to specify your package or packages.

Per [Modules](https://docs.python.org/3/tutorial/modules.html), what we're talking about here are Packages (directories with _\_\_init\_\_.py_, "a collection of modules"), not Modules ("a file containing Python definitions and statements").

2021-08-31 07:55 UTC, PierreGuilmin commented
I really think this would be a great adding to the documentation, as I just lost quite some time finding this information. I think @TBBle phrasing is the best, I can quickly write the new PR if this one keeps staling.

2021-11-14 05:21 UTC, neersighted requested changes
> 
> 
> I just bounced off exactly this problem, and eventually found this pending PR (via #2252) documenting exactly what I was doing wrong (`tool.poetry.name` wasn't the package name, and there was no prompt that this resulted in no packages being installed, just the listed dependencies).
> 
> That said, this text is maybe a little unclear, as it suggests that
> 
> > `tool.poetry.name` [is] specified within `tool.poetry.packages`
> 
> which is not the problem.
> 
> So perhaps
> 
> > Poetry assumes your package contains a packge with the same name as `tool.poetry.name`. If this is not the case, populate `tool.poetry.packages` to specify your package or packages.
> 
> Per [Modules](https://docs.python.org/3/tutorial/modules.html), what we're talking about here are Packages (directories with ___init__.py_, "a collection of modules"), not Modules ("a file containing Python definitions and statements").

I have to agree with the above -- @HallerPatrick, would you be willing to rephrase a bit along those lines?

2021-11-14 11:38 UTC, HallerPatrick commented
@neersighted updated the docs after the wording of @TBBle. Could you also maybe squash my upstream merge commits of my fork?

2021-11-14 11:43 UTC, TBBle approved these changes

2021-11-14 12:42 UTC, neersighted approved these changes

2021-11-14 12:53 UTC, merged