Deprecate to_str
python-poetry/poetry pull request #3298
Opened 2020-10-27 20:27 UTC by stephsamson

# Pull Request Check List

Resolves: #issue-number-here

- [x] Added **tests** for changed code.
- [x] Updated **documentation** for changed code.

2020-11-02 21:59 UTC, abn requested changes

2020-11-02 21:59 UTC, abn commented on poetry/utils/_compat.py
> -    encodings = ["utf-8", "latin1", "ascii"]
Should we handle this via `str(x, encoding=encoding)`? We should add a test case for PyPI repositories that evalueatets this.

2020-11-24 12:47 UTC, stephsamson commented
Closing for #3405

2020-11-24 12:47 UTC, closed without merging

2020-11-24 13:15 UTC, abn commented
@stephsamson #3405 did not remove the method though right? I think we still need  to remove encode/decode/to_str in a separate change.