Account for symlinked .venv when removing
python-poetry/poetry pull request #3375
Opened 2020-11-18 07:04 UTC by vibe

# Pull Request Check List

Resolves: Sometimes the `.venv` is a symlink, such as in caching strategies for CI/CD environments (codebuild, etc)  
Related: https://github.com/python-poetry/poetry/pull/2064

- [ X] Added **tests** for changed code.
- [ X] Updated **documentation** for changed code.

2020-11-18 08:54 UTC, vibe commented
Hmm, I see a test failed for 3.6 where the error code number is 2 and not 0.


Gross.

Maybe it's worth it to make the symlink check explicit instead of checking the code number...

2021-11-14 04:57 UTC, neersighted requested changes

2021-11-14 04:57 UTC, neersighted commented on tests/utils/test_env.py
> +            raise OSError(20, "Test error")  # ERRNO 16: Device or resource busy
Looks like this comment is incorrect.

2021-11-14 04:57 UTC, neersighted commented on poetry/utils/env.py
> +        # the venv folder is mounted or symlinked by the OS, such as in a docker volume, codebuild, etc. In such
Please reformat this comment block to have a uniform width.

2021-11-14 04:57 UTC, neersighted commented on poetry/utils/env.py
> +            if (
I'd like to see the `errno` module's named constants used here. A construct like `e.errno in (errno.ENOTDIR, errno.EBUSY)` would be more obvious and maintainable.

2021-11-14 04:57 UTC, neersighted commented on poetry/utils/env.py
>              # Continue only if e.errno == 16
Out of date comment

2021-11-14 04:57 UTC, neersighted commented on poetry/utils/env.py
> +        # See https://bugs.python.org/issue1669
I don't think this issue is relevant -- it describes a bug that is long-resolved, and not the behavior of throwing an exception when called on a symlink.

2021-11-14 04:57 UTC, neersighted commented on tests/utils/test_env.py
> +def test_remove_keeps_dir_if_not_deleteable_os_err_20(
Let's parameterize this whole test for different `errno` constants instead of doing this copy-and-paste.

2025-01-17 02:55 UTC, abn commented
Stale. Closing as this has not had any activity for a while, and the error the change attempts to fix is no longer reproducible.

2025-01-17 02:55 UTC, closed without merging