console: refactor export command
python-poetry/poetry pull request #3384
Opened 2020-11-19 14:35 UTC by abn

This change refactors export command to use format specific sub-command
instead of the previously used `--format` option.

Due to limitations of clikit/cleo, we manipulate `sys.argv` to detect
deprecated usage and route command to replicate current behaviour.

2020-11-19 14:45 UTC, abn commented
@sdispater Not sure if there is better way to do this with cleo; couple of issues I had to workaround were

1. Lack of a mechanism to specify a default fallback sub-command passing through the current options without raising a `NoSuchOption`. See workaround in `Application` implementation.
2. Lack of support for global options for subcommands when used with command tester. The workaround here was to move the options from global to sub-commands themselves (eg: `--output`).

2021-07-21 17:32 UTC, Leonardofreua requested changes

2021-07-21 17:32 UTC, Leonardofreua commented on poetry/console/application.py
> +                    )
```suggestion
                    self._preliminary_io.error_line(f"<fg=yellow>{message}</>\n")
```

2021-07-21 17:32 UTC, Leonardofreua commented on tests/exporter/test_exporter_requirements_txt.py
> +    exporter.export(Path(tmp_dir), "requirements.txt")
Consider putting the `requirements.txt` string into a constant.

2022-04-08 17:10 UTC, abn commented
This is no longer relevant here as the export command is being moved into the `poetry-plugin-export` package.

2022-04-08 17:10 UTC, closed without merging