Make get-poetry.py compatible with Cygwin - fix #1383
python-poetry/poetry pull request #3616
Opened 2021-01-29 15:36 UTC by Lucas-C

# Pull Request Check List

Resolves: #1383

- ❌ Added **tests** for changed code: no, as including tests for the Cygwin platform would require adding Cygwin as part of the GitHub Actions pipeline OS matrix: https://github.com/python-poetry/poetry/blob/master/.github/workflows/main.yml#L24
- ❌ Updated **documentation** for changed code: no, as the documentation currently does not mention Cygwin

2021-02-10 00:00 UTC, abn requested changes

2021-02-10 00:00 UTC, abn commented on get-poetry.py
> +        if platform == "cygwin":
Maybe move this into an else block?

2021-02-10 08:38 UTC, Lucas-C commented on get-poetry.py
> +        if platform == "cygwin":
You mean an `elif`?

2021-11-14 05:05 UTC, neersighted commented
Closing this as `get-poetry.py` is deprecated and frozen. Please test `install-poetry.py`/`install.python-poetry.org` and create issues for any deficiencies you find.

2021-11-14 05:05 UTC, closed without merging