doc: change bash completions to user directory
python-poetry/poetry pull request #3654
Opened 2021-02-05 21:03 UTC by dlech

This changes the recommendation for bash completions to install in the user's home directory instead of the global `/etc` which would require root access.

The expression is exactly how bash completions looks for the directory. Comes from: https://github.com/scop/bash-completion/blob/9e98e2558c0625340013b123880ebb6bedc0d1b3/bash_completion#L2262

Also a section is added about how to dynamically add the completions instead of creating a static file and describes the pros and cons of doing it that way instead.

Fixes #2295

# Pull Request Check List

Resolves: #issue-number-here

- [ ] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

2021-03-21 00:07 UTC, abn requested changes

2021-03-21 00:07 UTC, abn commented on docs/docs/index.md
> +poetry completions bash > ${BASH_COMPLETION_USER_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/bash-completion}/completions/poetry
```suggestion
BASH_COMPLETION_USER_DIR=${BASH_COMPLETION_USER_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/bash-completion}/completions
mkdir -p ${BASH_COMPLETION_USER_DIR}
poetry completions bash > ${BASH_COMPLETION_USER_DIR}/poetry
```

2021-03-21 00:07 UTC, abn commented on docs/docs/index.md
> +Poetry is updated. Alternatly, you can dynamically create the completions each time
```suggestion
Poetry is updated. Alternatively, you can dynamically create the completions each time
```

2021-03-21 00:07 UTC, abn commented on docs/docs/index.md
> +poetry completions bash > ${BASH_COMPLETION_USER_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/bash-completion}/completions/poetry
Might also want to mention the use of `/etc` as a way to add to all users for a system-wide install.

2021-03-23 22:51 UTC, dlech commented
Thanks for the review. I have made the requested changes.

2021-03-29 09:45 UTC, stephsamson approved these changes

2021-06-08 15:53 UTC, dlech commented
Anything else needed to get this merged?

2021-09-10 21:15 UTC, dlech commented
Looks like this bitrotted and I don't feel like updating since it doesn't seem like it was ever going to be merged anyway.

2021-09-10 21:15 UTC, closed without merging