feature(virtualenv): add 'system-site-packages' option
python-poetry/poetry pull request #3711
Opened 2021-02-20 22:04 UTC by vlad0337187

# Pull Request Check List

Resolves: #issue-number-here

- [+] Added **tests** for changed code.
- [+] Updated **documentation** for changed code.

2021-02-20 22:05 UTC, vlad0337187 commented
This is just a rebase to `master` for [already implemented PR](https://github.com/python-poetry/poetry/pull/1982) [for issue](https://github.com/python-poetry/poetry/issues/1393)

2021-03-03 12:07 UTC, meakbiyik commented
Great work, this commit will have a huge effect on my SSD capacity 😄

2021-03-11 09:51 UTC, vlad0337187 commented
@abn , could you review it please when you'll have some free time ?
Thanks.

2021-03-12 00:53 UTC, abn requested changes
Thank you @vlad0337187. The change looks good to me. I have added one comment to help with future code maintanence.

2021-03-12 00:53 UTC, abn commented on tests/utils/test_env.py
> +        flags={"always-copy": False, "system-site-packages": False},
Would be great to move this to a fixture so future additions or changes to defaults would be cleaner.

2021-03-17 19:13 UTC, henryiii commented
This also could be useful on Apple Silicon, where there are no NumPy wheels yet but most systems (homebrew, conda-forge) provide binaries for NumPy.

2021-03-21 00:48 UTC, abn approved these changes

2021-03-21 00:49 UTC, merged

2021-03-22 13:14 UTC, daevski commented
Thank you _all_!!! This will be very useful, I've been waiting on it ;)