Don't change poetry.lock during `poetry update --dry-run`
python-poetry/poetry pull request #3767
Opened 2021-03-10 15:35 UTC by martinmo

# Pull Request Check List

Resolves: #3766

- [x] Added **tests** for changed code.
- [x] Updated **documentation** for changed code.

AFAIK, there is no relevant documentation to be changed, am I right?

2021-03-10 15:38 UTC, martinmo commented
Linting fails on a file that is not touched in this PR (docs/docs/pyproject.md).

2021-03-21 12:11 UTC, abn commented
@martinmo can you rebase the branch please? Should fix the linting issues.

2021-03-21 12:12 UTC, abn requested changes
Needs a rebase to fix checks.

2021-03-22 12:49 UTC, martinmo commented
> Needs a rebase to fix checks.

Done ✅

2021-07-13 13:51 UTC, martinmo commented
I have rebased this to check if it works against the current code in `master`. This PR probably also fixes #3739 (`lock --dry-run`) and #3666 (`remove --dry-run`), or basically every command that has a `--dry-run` flag wrt to the lockfile and doesn't set the `force` parameter explicitely when calling `_write_lock_file(…)`.

2021-09-19 12:51 UTC, finswimmer commented
Hello @martinmo,

could you please rebase once more to force the tests running again?

Thanks!

fin swimmer

2021-09-20 08:24 UTC, martinmo commented
> Hello @martinmo,
> 
> could you please rebase once more to force the tests running again?
> 
> Thanks!
> 
> fin swimmer

Done ✅

2022-01-05 13:38 UTC, martinmo commented
> Hi @martinmo just checking on this and seeing if you had the time to push this through; it's a pretty annoying part of poetry! Thanks :)

Not yet, but I rebased and force pushed it again to see what the CI checks say.

2022-01-05 19:19 UTC, martinmo commented
Hi @abn could you please have another look at this PR? I rebased it and adjusted it to conform to the new coding guidelines. Thank you!

2022-01-06 15:58 UTC, martinmo commented
@finswimmer the review for this PR is somehow stuck. I saw that you have been active on other PRs in the last days, could you please have a look at this PR? It has a test for the changed behavior and all CI checks have passed. Thanks!

2022-01-19 12:04 UTC, dimitrismistriotis commented
Me + team affected from this, would be great if it could be progressed.

2022-04-05 05:59 UTC, zEdS15B3GCwq commented
I'm on 1.2.0b1 (current latest) and this issue persist. Please proceed with the PR. Much appreciated.

2022-04-05 15:21 UTC, radoering commented on tests/console/commands/test_update.py
> +def test_dry_run_update(
Can you please add similar tests (or extend existing tests) for the following commands (if not yet existing):

- `add --dry-run`
- `add --lock --dry-run`
- `remove --dry-run`

Further, it seems that tests for `add` check that the `pyproject.toml` is not changed for dry-run. Can you please add this check here, too?

2022-04-05 15:24 UTC, radoering commented on tests/console/commands/test_update.py
> +def test_dry_run_update(
And probably, you should rebase first before adding tests. 🙏

2022-05-29 18:33 UTC, closed without merging