Used pyupgrade to remove compatibility code
python-poetry/poetry pull request #3861
Opened 2021-03-30 18:57 UTC by ThatXliner

Relates-to: #3860

# Pull Request Check List

Resolves: #issue-number-here

- [N/A ] Added **tests** for changed code.
- [N/A ] Updated **documentation** for changed code.

2021-03-30 19:04 UTC, ThatXliner commented
Sorry for the messy commits!

2021-03-31 14:05 UTC, finswimmer requested changes
Thanks a lot @ThatXliner :1st_place_medal: 

Some minor suggestion where the conversion to f-string haven't worked well enough.

TIL: `yield from` :+1:

2021-03-31 14:05 UTC, finswimmer commented on poetry/puzzle/solver.py
> +                        ", ".join(f"({b})" for b in self._overrides)
```py
f"Resolved with overrides: {', '.join(f'({b})' for b in self._overrides)}"
```

2021-03-31 15:32 UTC, ThatXliner commented on poetry/publishing/uploader.py
> +                        " - Uploading <c1>{}</c1> <fg=green>%percent%%</>".format(
What's `%percent%%`

2021-03-31 16:07 UTC, finswimmer commented on poetry/publishing/uploader.py
> +                        " - Uploading <c1>{}</c1> <fg=green>%percent%%</>".format(
That's some magic `cleo` is doing: https://cleo.readthedocs.io/en/latest/helpers/progress_bar.html?highlight=percent#custom-formats

2021-03-31 16:45 UTC, ThatXliner commented on poetry/publishing/uploader.py
> +                        " - Uploading <c1>{}</c1> <fg=green>%percent%%</>".format(
So it's not [C-style string interpolation](https://docs.python.org/3/library/stdtypes.html#old-string-formatting), correct? In that case, I'll need to switch all the `"...{}...".format(..)` into f-strings

2021-03-31 16:57 UTC, ThatXliner commented
For line 83
https://github.com/ThatXliner/poetry/blob/cdf6d9beafc84768de574cd5b906834ebfe8aa38/poetry/puzzle/solver.py#L83
Should we keep it like that?

2021-04-02 16:13 UTC, finswimmer approved these changes
Thanks a lot for your contribution. Looks good to me :+1:

2021-04-02 16:13 UTC, merged