repository: dedupe logic
python-poetry/poetry pull request #3868
Opened 2021-03-31 19:16 UTC by abn

This change unifies shared logic across repository implementations.

2022-03-22 16:34 UTC, radoering commented on src/poetry/repositories/repository.py
> +        super().__init__(name)
```suggestion
        super().__init__(name, packages)
```

Then the rest of `__init__` can be dropped.

2022-04-05 16:09 UTC, tgolsson commented
Heyo @abn! 

We chatted ~two weeks ago on Discord re some issues I had with secondary sources, and you directed me here! Since this PR would make all my fixes pointless (you've removed a lot of the affected code) I wanted to wait until after this PR, but I'm curious when it'll get merged.

2022-04-05 17:01 UTC, abn commented
@tgolsson this is just waiting on a final review.

2022-04-08 13:58 UTC, radoering requested changes
Some general thoughts:

The methods `_links_to_data()`, `_get_response()`, `_get_page()` are defined in `HttpRepository` but are only used in `LegacyRepository` not `PypiRepository`. Is there a reason not to move them to `LegacyRepository`?

Considering the inheritance hierarchy:
```
BaseRepository
- Repository
  - InstalledRepository
  - TestRepository
- Pool
- CachedRepository
  - ...
```
Is `Repository` still required? I think its `__init__` and `find_packages` can be moved to `InstalledRepository`. `TestRepository` overrides `find_packages` anyway so it can inherit from `BaseRepository` directly. If I miss something and `Repository` is required, it should at least be renamed.

2022-04-08 13:58 UTC, radoering commented on src/poetry/repositories/http.py
> +        filename = os.path.basename(urllib.parse.urlparse(url).path.rsplit("/")[-1])
```suggestion
        filename = os.path.basename(wheel_name)
```

2022-04-08 13:58 UTC, radoering commented on src/poetry/repositories/http.py
> +        )
```suggestion
        self._log(f"Downloading sdist: {sdist_name_log}", level="debug")
```

2022-04-08 13:58 UTC, radoering commented on src/poetry/repositories/link_sources/html.py
> +        self._content = content
```suggestion
```

2022-04-08 13:58 UTC, radoering commented on src/poetry/repositories/link_sources/base.py
> +        return self._clean_re.sub(lambda match: f"%{ord(match.group(0)):02x}", url)
```suggestion
        return self.CLEAN_REGEX.sub(lambda match: f"%{ord(match.group(0)):02x}", url)
```

2022-04-08 13:58 UTC, radoering commented on src/poetry/repositories/link_sources/base.py
> +
```suggestion
```

2022-04-08 13:58 UTC, radoering commented on src/poetry/repositories/link_sources/base.py
> +            if pkg.name == name and pkg.version == version:
```suggestion
            if pkg.name == name and pkg.version and pkg.version == version:
```

2022-04-08 15:40 UTC, abn commented
I think unifiying `BaseRepository` and `Repository` makes sense. The original rationale was to keep the changes outside of `poetry.repositories` minimal. In retrospect that does not really matter.

As for inheritence, this is what it will look like eventually. Note the addition of find links related repositories, this is one of the reasons why some of the methods only used by legacy is in HTTP, as it conceptualyl makes sense for all HTTP backed repositories.

```

                                                              ┌───────────────────┐
                                                 ┌───────────►│InstalledRepository│
                                                 │            └───────────────────┘
                                                 │
                   ┌────────────────┐      ┌─────┴──────┐
                   │CachedRepository│◄─────┤ Repository ├──────────────────┐
                   └───────┬────────┘      └─────┬──────┘                  │
                           │                     │                         │
                           │                     │            ┌────┐       │
                           │                     └───────────►│Pool│       │
                           │                                  └────┘       │
                    ┌──────▼───────┐                                       │
         ┌──────────┤HTTPRepository├──────────────┐                        │
         │          └──────┬───────┘              │                        │
         │                 │                      │                        │
         │                 │                      │                        │
         │                 │                      │                        │
 ┌───────▼────────┐ ┌──────▼───────┐ ┌────────────▼──────────┐             │
 │LegacyRepository│ │PypiRepository│ │FindLinksHTMLRepository│             │
 └────────────────┘ └──────────────┘ └───────────────────────┘             │
         ▲                                 ▲                               │
         │                                 │                               │
         │                                 │                               ▼
         │                                 │          ┌────────────────────────────┐
         │             ┌────────┐          │          │FindLinksDirectoryRepository│
         └─────────────┤HTMLPage├──────────┘          └────────▲───────────────────┘
            used by    └────────┘   used by                    │
                           ▲                                   │ used by
                           │                                   │
                      ┌────┴─────┐                    ┌────────┴──────────┐
                      │LinkSource├───────────────────►│DirectoryLinkSource│
                      └──────────┘                    └───────────────────┘

```

2022-04-08 15:56 UTC, radoering approved these changes

2022-04-08 16:15 UTC, merged