Add a special error message for missing commands
python-poetry/poetry pull request #3884
Opened 2021-04-06 22:25 UTC by SeriousBug

If a given command is missing, `poetry run` would result in an exception being printed out.

This pull request adds an error message describing what the issue is.

closes #3883

# Pull Request Check List

Resolves: #issue-number-here

- [x] Added **tests** for changed code.
- [x] Updated **documentation** for changed code.

2021-04-07 00:25 UTC, abn requested changes
Minor suggestion.

2021-04-07 00:25 UTC, abn commented on poetry/console/commands/run.py
> +            self.line_error("")
```suggestion
            self.line_error(f "<error><c1>{script}</c1>: command not found.</error>")
```

Maybe something more concise is better?

2021-04-07 00:27 UTC, abn commented
Would be great if we can add a test case for this.

## Testing PR
### Using pipx
```sh
pipx install --suffix=@3884 'poetry @ git+https://github.com/python-poetry/poetry.git@refs/pull/3884/head'
poetry@3884 new foobar
cd foobar
poetru@3884 run does-not-exist
```

### Using a container (podman | docker)
```sh
podman run --rm -i --entrypoint bash python:3.8 <<EOF
set -xe
python -m pip install -q git+https://github.com/python-poetry/poetry.git@refs/pull/3884/head
poetry new foobar
pushd foobar
poetry run does-not-exist
EOF
```

2021-07-21 05:42 UTC, dimaqq commented
@SeriousBug would you consider pushing some kind of update, so that the builder runs again?
Sadly, the job result has expired, and none can see why it failed.

2021-07-21 17:26 UTC, Leonardofreua requested changes

2021-07-21 17:26 UTC, Leonardofreua commented on poetry/console/commands/run.py
> +            self.line_error(f "<error><c1>{script}</c1>: command not found.</error>")
Remove whitespace before starting the string:
```suggestion
            self.line_error(f"<error><c1>{script}</c1>: command not found.</error>")
```

2021-07-21 17:50 UTC, SeriousBug commented
I'm very busy right now and don't have the time to complete this pull request. If someone would like to see this change in poetry, please fork my repository and submit a new pull request.

2021-07-21 17:50 UTC, closed without merging