Use compatible Python executable installed by Pyenv
python-poetry/poetry pull request #4164
Opened 2021-06-09 16:24 UTC by ggicci

# Pull Request Check List

Resolves:  #4079

- [x] Added **tests** for changed code.
- [x] Updated **documentation** for changed code.

A new config item `virtualenvs.use-pyenv` with default value `true` has been instroduced. 

If no compatible versions were found in the system, poetry will keep looking for a compatible Python executable installed by `pyenv`.

Futher improvements can be done:

- [ ] If pyenv also has no compatible Pythons, prompt to ask user whether to install one by using `pyenv install` command.
- [ ] Use pyenv installed Pythons first, instead of using system ones. Which should be able to solve #4101

2021-06-10 03:53 UTC, ggicci commented
Test output here:

```bash
$ python2 -V
Python 2.7.17

$ python3 -V
Python 3.6.9

$ pyenv versions
* system (set by /home/mingjietang/.pyenv/version)
  3.7.10
  3.8.10
  3.9.4

$ cd ~/workspace/src/ggicci.me/poetry-pyenv-test
$ grep "python =" pyproject.toml
python = "~3.7"

$ poetry@local -vvv install
Loading configuration file /home/ggicci/.config/pypoetry/config.toml
The currently activated Python version 3.6.9 is not supported by the project (~3.7).
Trying to find and use a compatible version. 
Pyenv loaded: /home/ggicci/.pyenv/bin/pyenv
Trying python3
Trying python3.7
Trying /home/ggicci/.pyenv/versions/3.7.10/bin/python3.7
Using /home/ggicci/.pyenv/versions/3.7.10/bin/python3.7 (3.7.10)
Creating virtualenv poetry-pyenv-test-gx4qtdVT-py3.7 in /home/ggicci/.cache/pypoetry/virtualenvs
Using virtualenv: /home/ggicci/.cache/pypoetry/virtualenvs/poetry-pyenv-test-gx4qtdVT-py3.7
Installing dependencies from lock file

Finding the necessary packages for the current system
```

2021-07-21 17:01 UTC, Leonardofreua requested changes

2021-07-22 05:45 UTC, ggicci commented on poetry/utils/env.py
> +                    candidates.append("python" + python_to_try)
Thanks for this good suggestion. I never noticed this tip of performance improvement before.

2021-07-22 05:53 UTC, ggicci commented on poetry/utils/pyenv.py
> +        if self._command is not None:
I prefer putting "fast fail" branches of statements in the head of a method and leaving "main logic" at the last.

2021-12-03 10:19 UTC, closed without merging

2021-12-18 21:34 UTC, NickKaramoff commented
@ggicci why did you close this PR?

2021-12-19 08:48 UTC, ggicci commented
This pr brought too many changes and should break down into small pieces.