Fix #3139
python-poetry/poetry pull request #4448
Opened 2021-08-28 10:06 UTC by volgar1x

# Pull Request Check List

Resolves: #3139

- [ ] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

2021-11-15 00:59 UTC, neersighted requested changes

2021-11-15 00:59 UTC, neersighted commented on poetry/installation/installer.py
>              if op.job_type == "uninstall":
Let's DRY this up a bit. Something like:

```python
if not self._create_virtualenv and isinstance(op, (Update, Uninstall)):
    op.skip(f"Virtualenv creation disabled (during {op.job_type})")
    continue
```

2021-11-15 01:02 UTC, neersighted commented
I would also like some regression tests to validate this change -- it looks like there are reproduction instructions at the linked issue.

2022-09-10 07:49 UTC, Secrus commented
This PR targets closed issue and the `1.1` branch. Closing.

2022-09-10 07:49 UTC, closed without merging