Fix cache URLs on Windows
python-poetry/poetry pull request #4531
Opened 2021-09-21 03:39 UTC by serverwentdown

The previous implementation would fail to install packages on Windows
because it creates a `Path` starting with a slash. Such a `Path` is
invalid on Windows. Instead, use the utility function url_to_path.

# Pull Request Check List

Resolves: #4479

- [ ] Added **tests** for changed code.
  - Not sure how to write tests for this change. 
- [ ] Updated **documentation** for changed code.

2021-10-09 13:22 UTC, Ivoz commented
I wonder if we can create a testcase that will fail that this fixes?

2021-10-09 16:50 UTC, serverwentdown commented
@Ivoz do you know where to put full end-to-end tests (running poetry commands)?

2021-10-09 22:04 UTC, mrogaski commented
I confirmed that this fixes #4541.

2021-10-15 10:42 UTC, serverwentdown commented
@finswimmer @sdispater I'd like a review of this PR because this is a major issue for all Windows users

2021-10-20 13:00 UTC, serverwentdown commented
@Ivoz Oh you're right! Thanks for catching this lack of test coverage. I'll fix it after I sleep, but my main suspect is that fixture_dir returns a relative path hence the bug does not get triggered.

2021-10-25 15:46 UTC, abn submitted a review, later dismissed
Overall looks good. Some minor suggestions.

2021-11-12 13:39 UTC, serverwentdown commented
I have made changes a while back, need another review.
@abn? @sdispater?

2021-11-12 13:57 UTC, neersighted requested changes
This looks a lot better than the current code -- we're making a lot better use of duck typing while eliminating a rather silly corner case. There's still some `isinstance()`, but I think you've got it down to the bare minimum

I'm ready to merge this once it passes lint and is rebased onto the current `master` (the FreeBSD tests were fixed there) -- and please make sure to make the same post-review changes to your backport PR.

2021-11-12 13:57 UTC, neersighted commented on poetry/utils/pip.py
> +    path: Union[Path, Link],
I have to agree with @abn here -- that function is not long for the world, but for now, we'd like it to match -- when it's removed, the method of excision will be more obvious.

2021-11-12 15:02 UTC, neersighted commented
Looks like this still needs to be rebased to fix the merge conflicts and fix the failing FreeBSD tests. I'll review after that's complete.

2021-11-12 15:06 UTC, neersighted approved these changes

2021-11-12 15:07 UTC, merged

2021-11-12 15:08 UTC, neersighted commented
Merged! Thank you for your work on this -- and sorry that poetry has been broken so long!

2021-11-12 15:19 UTC, serverwentdown commented
Awesome, thanks for getting this finally merged! 🥳

2021-11-12 16:37 UTC, mario-bermonti commented
Great! Thanks for fixing this.