fix: `poetry env` broken on Windows (#4615)
python-poetry/poetry pull request #4682
Opened 2021-10-28 12:00 UTC by tom-bowles

Resolves: #4615

Looks like this if statement was copied from further up in the function and only one of the branches updated to use self._path.

2021-10-30 19:22 UTC, abn commented
@tom-bowles can you rebase this so the cirrus tests can have a rerun please?

2021-10-31 10:43 UTC, tom-bowles commented
@abn - Thanks for taking a look! I've rebased now.

2021-10-31 13:51 UTC, abn commented
@tom-bowles should have mentioned this earlier, any cance we can add in a test case for this so we do not regress?

2021-11-01 09:49 UTC, tom-bowles commented
@abn - no worries, I'll have a crack at that today

2021-11-01 14:52 UTC, tom-bowles commented
@abn - Added test.

2021-11-12 15:42 UTC, neersighted requested changes
LGTM -- we just need the formatting fixed (run `pre-commit run --all-files`) by black to merge.

2021-11-12 15:44 UTC, neersighted commented on tests/utils/test_env.py
> +    assert Path(venv.python) == base_dir_path
Looks like this test fails on Python 3.6 on Windows, so I spoke a little too soon. Can we take a look at that failure and get it corrected?

2023-03-12 18:06 UTC, dimbleby commented
Looks like this was fixed incidentally at #5007.

Apparently that one was allowed through without testcases so I suppose it could _just about_ be worth keeping this open if anyone is motivated, more than a year later, to add a unit test.

But I expect this should now be closed.

2024-10-14 21:22 UTC, closed without merging