Improvement/force type hints
python-poetry/poetry pull request #4775
Opened 2021-11-16 15:55 UTC by finswimmer

# Pull Request Check List

Resolves: #issue-number-here

- [ ] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

2021-11-18 14:10 UTC, neersighted requested changes
LGTM!

One question, besides the whitespace nit-picking:
Can/should we turn on Mypy for the affected modules, now that they are fully hinted? As best I can tell, nothing is actually checking that these new hints are correct at the moment.

2021-11-18 15:34 UTC, finswimmer commented on pyproject.toml
> +typing-extensions = {version = "^4.0.0", python = "<3.8"}
Because this is how `poetry add` inserted it, I would prefer leaving it like it is.

2021-11-18 15:40 UTC, finswimmer commented
> One question, besides the whitespace nit-picking: Can/should we turn on Mypy for the affected modules, now that they are fully hinted? As best I can tell, nothing is actually checking that these new hints are correct at the moment.

I let mypy inspect these modules. Some of the errors seems to be due to incorrect typings in the application code. This is why I suggest we first fix mypy errors there and have a look at the tests afterwards.

It looks like there are also some tricky errors, e.g.

```
tests/console/commands/test_show.py:1524: error: "Locker" has no attribute "mock_lock_data"; maybe "_lock_data" or "lock_data"?
```

This is because the `Poetry` object gets a `TestLocker` injected, which inherits from `Locker` but has some additional methods. Not sure how to teach this to mypy ...

TL;DR: Let us postpone mypy checks for the tests modules.

2021-11-19 14:16 UTC, neersighted approved these changes

2021-11-19 14:16 UTC, merged