Use flake8 type checking
python-poetry/poetry pull request #4787
Opened 2021-11-17 14:46 UTC by radoering

# Pull Request Check List

Relates-to: #4776

2021-11-17 15:03 UTC, neersighted requested changes
Awesome! I like this a lot more than I even thought I would -- it really makes the usage of imports unambiguous.

A few corrections/nits to pick, and then also one question -- since upstream seems open to adding a whitelist, is it worth adding those so we can drop `# noqa`? The good news is when the whitelist is added, yesqa should automate removing those comments.

Alternatively, there is https://pypi.org/project/future-annotations/, but I'm not sure how it will interact with the rest of our tooling.

2021-11-17 15:03 UTC, neersighted commented on src/poetry/utils/password_manager.py
> +from typing import Dict  # noqa: TC002  # noqa: TC002
Looks like the `# noqa` got added twice here.

2021-11-17 15:51 UTC, radoering commented on src/poetry/masonry/builders/__init__.py
> +from poetry.masonry.builders.editable import EditableBuilder  # noqa: TC002
Not sure. Probably, suitable for most `__init__.py` files. However, some files like `poetry/mixology/__init__.py` should probably not be excluded. Maybe, the same applies to `F401`. 🤷‍♂️ I'll change it if you like.

2021-11-17 17:14 UTC, radoering commented
> A few corrections/nits to pick, and then also one question -- since upstream seems open to adding a whitelist, is it worth adding those so we can drop `# noqa`? The good news is when the whitelist is added, yesqa should automate removing those comments.

I'll try the whitelist as soon as it has been added upstream. That should remove a lot of `# noqa`.

2021-11-18 12:39 UTC, finswimmer approved these changes
Beautiful :heart_eyes:

2021-11-18 12:40 UTC, merged