Add 1.1.11 and 1.1.12 to CHANGELOG.md
python-poetry/poetry pull request #5182
Opened 2022-02-10 21:57 UTC by remram44

# Pull Request Check List

- `n/a` Added **tests** for changed code.
- `n/a` Updated **documentation** for changed code.
- [x] This PR changes no code

I took the info from the GitHub releases page. I couldn't find any info for 1.1.13, so I didn't add it.

See also #4554

2022-02-11 05:51 UTC, finswimmer requested changes
Hello @remram44,

thanks for porting this data. I've added the 1.1.13 info to the release page as well. You could find all these data in the `CHANGELOG.md` of the 1.1 branch as well: https://github.com/python-poetry/poetry/blob/1.1/CHANGELOG.md

fin swimmer

2022-02-25 21:49 UTC, finswimmer requested changes

2022-02-25 21:49 UTC, finswimmer commented on CHANGELOG.md
> +- Fixed an issue where envs in MSYS2 always reported as broken ([#4942](9https://github.com/python-poetry/poetry/pull/4942))
```suggestion
- Fixed an issue where envs in MSYS2 always reported as broken ([#4942](https://github.com/python-poetry/poetry/pull/4942))
```

2022-02-25 21:51 UTC, remram44 commented on CHANGELOG.md
> +- Fixed an issue where envs in MSYS2 always reported as broken ([#4942](9https://github.com/python-poetry/poetry/pull/4942))
Error exists on `1.1` branch too

2022-02-25 21:59 UTC, finswimmer approved these changes
Thanks a lot :+1:

2022-02-25 22:00 UTC, merged

2022-02-25 22:12 UTC, tony commented
@finswimmer minor fix for the heading (i didn't catch this initially) #5237