Allow any file extension for README file
python-poetry/poetry pull request #5357
Opened 2022-03-24 21:07 UTC by s-spindler

# Pull Request Check List

Resolves: 5356

- [x] Added **tests** for changed code.
- [x] Updated **documentation** for changed code.

2022-05-18 03:06 UTC, neersighted requested changes
I'm fine with this -- looks like it just needs a little touchup and it's good.

2022-05-18 03:06 UTC, neersighted commented on docs/cli.md
> +* `--readme`: Specify the readme file format. Default is `md`.
```suggestion
* `--readme`: Specify the readme file extension. Default is `md`.
```

2022-05-24 10:24 UTC, Secrus commented
I think it would be good to add a warning or note in `pyproject` docs, that formats different from md or rst might not be processed correctly on official PyPI.

2022-05-24 11:05 UTC, s-spindler commented
I added @neersighted's suggestion and added a sentence as suggested by @Secrus.

2022-05-24 17:23 UTC, neersighted submitted a review, later dismissed

2022-05-27 22:46 UTC, Secrus commented
@s-spindler please fix the pre-commit problem so we could merge this.

2022-05-29 13:09 UTC, Secrus approved these changes

2022-05-29 13:31 UTC, merged