Issue #4667: msft has a different bin directory for python
python-poetry/poetry pull request #5433
Opened 2022-04-09 16:14 UTC by Charlieung

# Pull Request Check List

Resolves: #4667 

Just adds another condition to check if it's in the default MSFT directory, which doesn't have the default /bin path for the python executable.

2022-05-03 22:50 UTC, TechnoTalksDev approved these changes
Seems great to help with Microsoft Store installs

2022-06-04 04:56 UTC, neersighted requested changes

2022-06-04 04:56 UTC, neersighted commented on src/poetry/utils/env.py
> +        self._bin_dir = self._path if self._is_windows_from_microsoft_store else self._path / bin_dir
```suggestion
        self._bin_dir = self._path
        if not self._is_windows_from_microsoft_store:
            self._path /= bin_dir
```

2022-08-24 09:18 UTC, chumbert commented
I'd be interested in seeing this merged.

If @Charlieung isn't active here anymore I can open another PR with the changes suggested by @neersighted.

2022-08-24 09:34 UTC, finswimmer commented
@chumbert: Please test it with 1.2.0rc1. Might be that this is solved already by another PR.

2025-01-17 03:31 UTC, abn commented
The MS store version does have [other issues](https://docs.python.org/3/using/windows.html#redirection-of-local-data-registry-and-temporary-paths) as well. The python.org version is probably preferred for development environments. Additionally, I suspect the original issue this PR set out to fix is no longer present.

2025-01-17 03:31 UTC, closed without merging