improve http request handling for sources and support multiple paths on same netloc
python-poetry/poetry pull request #5518
Opened 2022-04-29 13:17 UTC by abn

This change refactors HTTP repository source implementations. The following changes have been made.

- CacheControl cache now lives within Authenticator.
- Authenticator manages unique sessions for individual netloc.
- CacheControl usage now respects disable cache parameter in repos.
- Certificate and authentication logic is now managed solely within
  Authenticator for source repositories taking advantage of recent
  enhancements.
- Support same netloc with multiple path's in Authenticator.
- Clean up and unifiy redundant logic in credential access.

These changes should allow for better handling of cases like those described in #3041. Additionally, this forms the foundation for unifying HTTP specific logic within the code base and possibly allowing for migration of requests etc. if/when required.

Additionally, also cleans up some type hinting issues pertaining to http repo only attributes.

Co-Authors: @Darsstar @agni-sairent

Closes: #5108
Closes: #5463

2022-04-29 17:30 UTC, abn commented
@Darsstar :cake: Thank you for testing that much appreciated and for the #5463. 

@agni-sairent would you mind if I pulled in your changes into this PR so its all tidy? I am guessing the use case things like gitlab etc where there are project specific credentials?

2022-04-29 17:46 UTC, agni-sairent commented
@abn go for it! I don't mind at all :smile: 
You're exactly right, our use case is multiple gitlab repos/package registries with different credentials.

2022-04-29 22:28 UTC, abn commented
@Darsstar @agni-sairent I have landed that change at https://github.com/abn/poetry/pull/1 for now - might need a couple of iterations. Feedback/testing appreciated. I just reused tests from #5463 - well, whatever was net new.

2022-05-04 16:17 UTC, KundaPanda commented
I am looking forward to seeing either one of these PRs merged, so I went forward and tried your version but discovered some odd behaviour.

- If I specify a custom source, which only contains specific packages, and I try to install another package from pypi (in my case, pytz), poetry cannot resolve it. (`Because test depends on pytz (^2022.1), which doesn't exist, version solving failed.`) This issue disappears once I have removed the source from pyproject.toml. After adding custom source(s) back, the issue arises again. All custom repositories are set as secondary, and adding an official pypi source as default did not help either.

- Custom packages need to be specified with source; otherwise, poetry only looks on pypi.org and fails with 404.

2022-05-06 09:54 UTC, Darsstar requested changes
Almost there! Lots of nice refactoring!

2022-05-06 09:54 UTC, Darsstar commented on src/poetry/utils/authenticator.py
> +            repository.get_http_credentials(password_manager=self._password_manager)
How about adding `_get_credentiald_for_repository(self, repository)` which caches the result in `self._credentials[repository.url]`?
That should save keyring lookups when downloading multiple deps from the same repo.

2022-05-06 09:54 UTC, Darsstar commented on tests/utils/test_authenticator.py
> +    assert request.headers["Authorization"] == f"Basic {basic_auth}"
This should define multiple repositories. Something like this:
```suggestion
    config.merge(
        {
            "repositories": {
                "alpha": {
                    "url": "https://foo.bar/org-alpha/_packaging/feed/pypi/simple/"
                },
                "beta": {
                    "url": "https://foo.bar/org-beta/_packaging/feed/pypi/simple/"
                },
            },
            "http-basic": {
                "alpha": {"username": "foo", "password": "bar"},
                "beta": {"username": "baz", "password": "qux"},
            },
        }
    )

    authenticator = Authenticator(config, NullIO())

    authenticator.request(
        "get",
        "https://foo.bar/org-alpha/_packaging/GUID/pypi/simple/a/1.0.0/a-1.0.0.whl",
    )
    request = http.last_request()

    basic_auth = base64.b64encode(b"foo:bar").decode()
    assert request.headers["Authorization"] == f"Basic {basic_auth}"

    authenticator.request(
        "get",
        "https://foo.bar/org-beta/_packaging/GUID/pypi/simple/b/1.0.0/a-1.0.0.whl",
    )
    request = http.last_request()

    basic_auth = base64.b64encode(b"baz:qux").decode()
    assert request.headers["Authorization"] == f"Basic {basic_auth}"

```

You could do a second request to the aplha repo if you want

2022-05-06 11:32 UTC, Darsstar submitted a review, later dismissed

2022-05-07 16:44 UTC, neersighted approved these changes

2022-05-07 16:44 UTC, merged