Add example for each section of `pyproject.toml`
python-poetry/poetry pull request #5585
Opened 2022-05-09 23:17 UTC by gunungpw

# Pull Request Check List

Resolves: #issue-number-here -> not found maybe I use wrong keyword :)

- [x] Added **tests** for changed code. -> None
- [x] Updated **documentation** for changed code. -> None

Hello, thank you for Poetry project. One of papercut in poetry docs was examples for simple section in `pyproject.toml` like `authors`, `maintainers` need to use `list` and `<>` to point email. For beginner like me, this example will help them to more understand how to fill the `pyproject.toml`.
Also another questions how to write multiple maintainer?

```toml
maintainer = [
    "Apple Juice <apple@juice.org>",
    "Orange Juice <orange@juice.org>",
]
```
Did example right, do I need use trailing comma, how about whitespace do toml use `space` or `tabs`. Maybe  I need to read toml spec ;)

2022-05-10 20:32 UTC, dimbleby commented on docs/pyproject.md
> +license = [
oops

2022-05-11 08:00 UTC, gunungpw commented on docs/pyproject.md
> +license = [
my bad :)

2022-05-18 03:40 UTC, neersighted requested changes

2022-05-18 03:40 UTC, neersighted commented on docs/pyproject.md
> +    "Sébastien Eustace <sebastien@eustace.io>"
Please add a trailing comma -- it's generally TOML best practice when you split a list over multiple lines like this.

2022-05-18 03:40 UTC, neersighted commented on docs/pyproject.md
> +    "Richard Brave <email@example.org>"
Ditto

2022-05-18 03:40 UTC, neersighted commented on docs/pyproject.md
> +description = "The description of the package"
```suggestion
description = "A short description of the package."
```

2022-05-18 04:43 UTC, gunungpw commented
Okay issue have been fix :)

2022-05-18 05:02 UTC, neersighted approved these changes

2022-05-18 05:05 UTC, merged