Add name field reference to PEP 508
python-poetry/poetry pull request #5642
Opened 2022-05-19 02:11 UTC by gunungpw

# Pull Request Check List

Resolves: #5267 

- [x] Added **tests** for changed code.
- [x] Updated **documentation** for changed code.

Add documentation for name field reference to [PEP 508](https://peps.python.org/pep-0508/#names)

2022-05-19 08:37 UTC, Secrus requested changes
Small formatting and grammar changes.

2022-05-19 08:37 UTC, Secrus commented on docs/pyproject.md
> +This should be valid name according to specifications in [PEP 508 - Names](https://peps.python.org/pep-0508/#names)
```suggestion

This should be a valid name according to specifications in [PEP 508 - Names](https://peps.python.org/pep-0508/#names)
```

2022-05-19 09:10 UTC, gunungpw commented on docs/pyproject.md
> +This should be valid name according to specifications in [PEP 508 - Names](https://peps.python.org/pep-0508/#names)
My bad english not my first language 👍

2022-05-19 09:12 UTC, Secrus submitted a review, later dismissed

2022-05-19 14:54 UTC, neersighted requested changes

2022-05-19 14:54 UTC, neersighted commented on docs/pyproject.md
> +This should be a valid name according to specifications in [PEP 508 - Names](https://peps.python.org/pep-0508/#names)
```suggestion
This should be a valid name as defined by [PEP 508](https://peps.python.org/pep-0508/#names).
```

2022-05-20 10:40 UTC, abn approved these changes

2022-05-20 10:41 UTC, merged