Test against Python 3.11
python-poetry/poetry pull request #5749
Opened 2022-06-01 22:10 UTC by mkniewallner

# Pull Request Check List

- ~[ ] Added **tests** for changed code.~ Not applicable
- ~[ ] Updated **documentation** for changed code.~ Not applicable

Since Python 3.11 reached a beta state, it would be nice to start running the test suite against it, to ensure that Poetry works as expected on this version when the final version is out.

It was not really feasible to do that earlier with `3.11.0b1` because of https://github.com/python-poetry/poetry/issues/5597 (and the associated upstream issue).

`3.11.0b2` was recently [released](https://www.python.org/downloads/release/python-3110b2/), fixing the issue, but unfortunately, it broke `pytest`, as reported in https://github.com/pytest-dev/pytest/issues/10008 (with a temporary workaround to fix it by passing `--assert=plain`).

`3.11.0b3` was [released](https://www.python.org/downloads/release/python-3110b3/) quickly after, which fixes the issue, but we have to wait for it to be available in https://github.com/actions/python-versions, hence why this PR is in draft (better wait a few days, to avoid the need for `--assert=plain` workaround).

The good news is that the tests all pass on Python 3.11 :tada: 

Once `3.11.0b3` is available on GitHub Actions, I'll update the PR to use it and remove the workaround.

2022-06-01 22:47 UTC, mkniewallner commented
> @mkniewallner
> 
> > Once `3.11.0b3` is available on GitHub Actions, I'll update the PR to use it and remove the workaround.
> 
> You can use the `-dev` suffix, i.e. `3.11-dev`: https://github.com/actions/setup-python#available-versions-of-python

Interesting, I was not aware of that, thanks!

Though by using `-dev`, won't this will still look for the latest alpha/beta release available in https://github.com/actions/python-versions/blob/main/versions-manifest.json, or is it doing something else?

The downside I can see with using `-dev` is that having a new alpha/beta release could out of the blue break the CI workflow (although the upside is that you automatically pick up the last version without needing to change anything, which is nice if a new version works as expected).

2022-06-01 22:54 UTC, edgarrmondragon commented
> Though by using `-dev`, won't this will still look for the latest alpha/beta release available in https://github.com/actions/python-versions/blob/main/versions-manifest.json, or is it doing something else?

It's doing just doing that, but the advantage is you don't need to go back and update the version in your workflows. Once `3.11.0b3` is available in `python-versions`, `3.11-dev` will point to it.

2022-06-02 20:03 UTC, neersighted requested changes

2022-06-02 20:03 UTC, neersighted commented on .github/workflows/main.yml
> +        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11.0-beta.3"]
I'd like to use `3.11-dev` as our version here unless there's a compelling reason to pin to one beta version -- a moving target is arguably a better smoke test for us than a pinned release.

2022-06-02 20:03 UTC, neersighted commented on .github/workflows/skip.yml
> +        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11.0-beta.3"]
As above.

2022-06-02 20:15 UTC, neersighted approved these changes

2022-06-02 20:15 UTC, merged