docs: Add paragraph about @ operator
python-poetry/poetry pull request #5822
Opened 2022-06-09 23:20 UTC by Secrus

Resolves: #5136 
Resolves: #3142

Added documentation on `@` operator in dependency specification.

2022-06-11 00:27 UTC, clintonroy commented on docs/dependency-specification.md
> +You can specify requirements, using `@` operator. This is understood the same way as `==` specifier, with one difference.
using the '@' operator, maybe

2022-06-11 00:28 UTC, clintonroy commented on docs/dependency-specification.md
> +After `@` symbol, you can use any specifiers that are valid in `pyproject.toml` file. For example:
After the '@' symbol, maybe.

Also, maybe best to stick with operator or symbol throughout.

2022-06-11 00:29 UTC, clintonroy commented on docs/dependency-specification.md
> +Would translate to following entry in `pyproject.toml`:
Would translate through to the following entry in pyproject.toml

2022-06-15 19:40 UTC, Secrus commented
@clintonroy I have addressed your comments.

2022-06-15 21:20 UTC, neersighted commented
I'm wondering if this is really the correct place to add the docs -- since there's no surrounding mention of `poetry add` it feels out of place. If this really is the best place then the opening sentence/section title should probably be something along the lines of "adding packages with constraints using the CLI" -- if there's a more natural location with other CLI docs, we should just add a link to that section.

2022-06-19 14:02 UTC, Secrus commented
@neersighted I added link in `add` command docs and changed first paragraph of the `@` documentation.

2022-06-19 19:16 UTC, neersighted requested changes

2022-06-19 19:16 UTC, neersighted commented on docs/dependency-specification.md
> +When adding dependencies via CLI `add` command, you can use `@` operator.
```suggestion
When adding dependencies via CLI `add` command, you can use the `@` operator.
```

2022-06-19 19:16 UTC, neersighted commented on docs/dependency-specification.md
> +specifiers that are valid in `pyproject.toml` file. For example:
```suggestion
This is understood similarly to the `==` syntax, but also allows prefixing any
specifiers that are valid in `pyproject.toml`. For example:
```

2022-06-19 19:16 UTC, neersighted commented on docs/cli.md
> +See the [Dependency specification]({{< relref "dependency-specification#using-the--operator" >}}) page for more information about `@` operator.
```suggestion
See the [Dependency specification]({{< relref "dependency-specification#using-the--operator" >}}) page for more information about the `@` operator.
```

2022-06-19 19:16 UTC, neersighted commented on docs/dependency-specification.md
> +For example:
```suggestion
The special keyword `latest` is also understood by the `@` operator:
```

2022-06-19 19:16 UTC, neersighted commented on docs/dependency-specification.md
> +Would translate to the following entry in `pyproject.toml`:
```suggestion
The above would translate to the following entry in `pyproject.toml`:
```

2022-06-19 19:16 UTC, neersighted commented on docs/dependency-specification.md
> +Would translate to the following entry in `pyproject.toml`:
```suggestion
The above would translate to the following entry in `pyproject.toml`, assuming the latest release of `django` is `4.0.5`:
```

2022-06-19 19:16 UTC, neersighted commented on docs/dependency-specification.md
> +To use extras for package using the `@` operator, formula is: `package[extra]@version`, for example:
```suggestion
Extras and `@` can be combined as one might expect (`package[extra]@version`):
```

2022-06-19 22:14 UTC, neersighted commented on docs/dependency-specification.md
> +When adding dependencies via CLI `add` command, you can use the `@` operator.
```suggestion
When adding dependencies via `poetry add`, you can use the `@` operator.
```

2022-06-19 22:15 UTC, neersighted approved these changes

2022-06-19 22:16 UTC, merged