Clarifying `scripts` section in docs
python-poetry/poetry pull request #5884
Opened 2022-06-20 21:21 UTC by Secrus

# Pull Request Check List

Replaces: #4071

Original code by graingert

2022-06-20 21:36 UTC, graingert submitted a review, later dismissed

2022-06-21 04:51 UTC, neersighted requested changes

2022-06-21 04:51 UTC, neersighted commented on docs/pyproject.md
> +Here, we will have the `my_package_cli` script installed which will execute `run` function in the `console` module in the `my_package` package.
```suggestion
Here, we will have the `my_package_cli` script installed which will execute the `run` function in the `console` module in the `my_package` package.
```

2022-06-21 10:52 UTC, merged

2022-06-21 11:33 UTC, graingert commented
Thanks for getting this in for me! I'm sorry I totally forgot about it