Turn spaces in project name to underscore.
python-poetry/poetry pull request #6085
Opened 2022-07-28 13:15 UTC by Ninzero

# Pull Request Check List

Currently, if the project name you typed contains whitespaces, the package name will also contain whitespaces. For example:

```
poetry new "New Project"
```

will cause test file contain:

```
from new project import __version__
```

which will cause error. In this case, we should automatically change project name to `new_project`.

I know that set `--name` argument can solve this problem. But I think maybe this process can be automated.

- [ ] Added **tests** for changed code.

I have not include a tests for this PR. Mainly because I have not figured out a suitable testing method, also because this is a draft PR. If anyone have good idea on how to test, please help, thanks.

- [ ] Updated **documentation** for changed code.

No documentation change required for this PR.

2022-09-18 17:52 UTC, neersighted commented
This change as-is is much too specific and hardcoded to the particular issue you sought to solve. We should likely normalize all project names during `poetry new` (e.g. see the `canonicalize_name()` function in `packaging.utils` that was most recently discussed in https://github.com/python-poetry/poetry/pull/6022), or reject them outright if they don't meet validity criteria.

2022-09-18 17:53 UTC, neersighted requested changes
This change as-is is much too specific and hardcoded to the particular issue you sought to solve. We should likely normalize all project names during `poetry new` (e.g. see the `canonicalize_name()` function in `packaging.utils` that was most recently discussed in https://github.com/python-poetry/poetry/pull/6022), or reject them outright if they don't meet validity criteria.

2022-10-24 13:30 UTC, Ninzero commented
I see. Since [PEP 426](https://peps.python.org/pep-0426/#name) only indicated which characters are allowed in package names. Maybe we should reject all package name with any invalid characters in it (by throwing an error)?

2022-11-23 20:14 UTC, neersighted commented
Closing as this is not mergable; a check for invalid characters in a pretty name (`name =` is a pretty name and not a canonicalized name) would likely be welcome, however.

2022-11-23 20:14 UTC, closed without merging