fix: fix failing tests due to updated list of available pythons
python-poetry/poetry pull request #6561
Opened 2022-09-19 10:02 UTC by finswimmer

Requires: https://github.com/python-poetry/poetry-core/pull/477

2022-09-24 16:55 UTC, mkniewallner approved these changes

2022-09-24 17:15 UTC, neersighted requested changes
It feels like it would make more sense to interrogate core for the Python versions and check that they are all reflected in the markers. Are we opposed to doing that, instead of hardcoding the output?

2022-10-04 16:11 UTC, radoering commented
I took a quick look and it seems "interrogating core for the versions" works only for the test in `test_editable_builder.py`. In `test_factory.py` it's not all versions from `AVAILABLE_PYTHONS`, but only the versions which are supported by the project. So it's actually reimplementing `all_classifiers` (or comparing it to itself). Thus, maybe just keep it hardcoded in both places.

2022-10-04 17:20 UTC, finswimmer commented
I came to the same conclusion as @radoering, but forget to answer.

2022-10-04 17:23 UTC, radoering approved these changes

2022-10-04 17:28 UTC, merged