Handle distribution.files being None
python-poetry/poetry pull request #6877
Opened 2022-10-24 10:19 UTC by jace-ys

# Pull Request Check List

Resolves: #6788 

We discovered that in some unknown situations, `distribution.files` can be `None`, causing the assertion to fail. To handle `distribution.files` being `None` more gracefully, we treat it as if it were an empty list.

- [ ] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

2022-10-24 14:38 UTC, neersighted requested changes
I do think this change is a bit clunky, I'd much rather do something like:

```py
if not distribution.files:
    break
```

Otherwise, the spirit of the thing looks good to me.

2022-10-24 15:31 UTC, jace-ys commented
Thanks for the suggestion @neersighted, definitely much neater than what I had - fixed it 👍🏻

2022-10-24 15:57 UTC, jace-ys commented
Good catch! Just updated it.

2022-10-24 22:23 UTC, dimbleby commented
this looks suspect in the third place you've done it: we now don't execute the code after the `for file in distribution.files`, which we previously did for an empty list.

fwiw I preferred the original version of this MR that went `files = [] if distribution.files is None else distribution.files`...

2022-10-25 09:20 UTC, jace-ys commented
@dimbleby Yeah good point. I think `files = [] if distribution.files is None else distribution.files...` has the benefit that it would easily solve the problem you highlighted.

I don't write Python much so don't have strong opinions on which approach is preferred - happy to defer to you folks!

2022-10-25 12:48 UTC, jace-ys commented
@neersighted Are you happy for me to revert it back to the original `files = [] if distribution.files is None else distribution.files` version?

Otherwise, I think the other option is to nest the inner for loo:
```
if distribution.files is not None:
    for file in distribution.files:
...
```

2022-10-25 14:12 UTC, neersighted commented
Ah, good catch, I skimmed too quickly there as well :laughing:

Yeah, I'd rather just indent/nest the for loop than create an empty list, but that's my personal preference.

2022-10-25 21:52 UTC, jace-ys commented
I've reverted it back to the original version I had 👍🏻

2022-10-28 19:17 UTC, neersighted approved these changes

2022-11-03 05:20 UTC, merged

2022-11-29 14:00 UTC, leocwolter commented
Hey, are there any workarounds we can use before this is released?

2022-12-03 08:58 UTC, ffreemt commented
Yeah, any workarounds? Am also struggling with a similar situation.

2022-12-03 13:54 UTC, leocwolter commented
Hey, I just noticed that this only happens when installing poetry via apt.
If you install it using the official installation script it works fine
(that was the case for me at least)


On Sat, Dec 3, 2022, 05:58 mikey ***@***.***> wrote:

> Yeah, any workarounds? Am also struggling with a similar situation.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/python-poetry/poetry/pull/6877#issuecomment-1336117471>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAKKYRQ55XAO3DH5KH6DLGLWLMDUHANCNFSM6AAAAAARM2PPLA>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2022-12-03 16:50 UTC, neersighted commented
> Hey, are there any workarounds we can use before this is released?
#7137 is under review, we should be releasing shortly.

> Hey, I just noticed that this only happens when installing poetry via apt.

Versions of Poetry distributed by distro packagers are unsupported and carry untested patches. Poetry's test suite is stripped by Debian and not run to validate their changes. We can provide no support for distro-packaged versions of Poetry.