fix(cli): make config relocation instructions more explicit
python-poetry/poetry pull request #7140
Opened 2022-12-04 12:28 UTC by cpate4

Fixes #6864

# Pull Request Check List

Resolves: #6864

- [ ] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

2022-12-20 20:52 UTC, cpate4 commented
pre-commit.ci autofix

2022-12-20 20:57 UTC, Secrus requested changes

2022-12-20 20:57 UTC, Secrus commented on src/poetry/locations.py
> +            " moving toml configuration files to %s, as support for the legacy"
```suggestion
            " moving TOML configuration files to %s, as support for the legacy"
```

2022-12-20 21:10 UTC, cpate4 commented
Thank you, @Secrus, for the feedback!

2023-01-22 21:01 UTC, Secrus commented
@cpate4 could you please resolve the conflict?

2023-01-22 21:45 UTC, Secrus commented
pre-commit.ci autofix

2023-01-22 21:54 UTC, Secrus approved these changes

2023-01-22 21:54 UTC, merged

2023-01-23 11:20 UTC, cpate4 commented
@Secrus - Thank you! This is my first (ever) open source contribution. 🙂