fix: append subdirectory to archive path (#7575)
python-poetry/poetry pull request #7580
Opened 2023-03-01 10:14 UTC by harrymander

Resolves: #7575

- [x] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code. (N/A)

From @nikowatari's suggestion (https://github.com/python-poetry/poetry/issues/755#issuecomment-1449275865) with added test.

2023-03-03 16:17 UTC, radoering requested changes
LGTM.

In addition, I think we can remove https://github.com/python-poetry/poetry/blob/3e32a4f83e89b2b2bede68e0d375a70931b04a8e/src/poetry/installation/executor.py#L589-L596

because this part was supposed to consider the subdirectory but apparently it does nothing.

2023-03-03 16:20 UTC, radoering commented
Actually, if we remove this code, we don't need `_prepare_directory_archive` at all, but can call `_prepare_archive` directly. 🤔

2023-03-03 21:55 UTC, harrymander commented
Yep those lines do nothing... have removed

2023-03-04 13:52 UTC, radoering approved these changes

2023-03-04 13:53 UTC, merged