Fix generate_system_pyproject newline issues
python-poetry/poetry pull request #7705
Opened 2023-03-22 22:57 UTC by NimajnebEC

# Addressed Issues

### Additional Carriage Returns
tomlkit persists the original line separators for the preserved tables, as a result these lines will be separated by `\r\n` on WIndows. Since the `newline` kwarg is omitted from the `self.system_pyproject.write_text`<sup>[[1]](https://github.com/python-poetry/poetry/blob/71b3d6e030c879f0b4b8e3a08eac2b38a402b6bd/src/poetry/console/commands/self/self_command.py#L80)</sup> method call, all occurrences of `\n` are replaced by `os.linesep`<sup>[[2]](https://docs.python.org/3/library/functions.html#open)</sup> before writing. This causes the resultant line separators for the preserved lines to be `\r\r\n`  on Windows.

These additional carriage returns become an issue when the file is parsed by tomli, which replaces only `\r\n` with `\n`,<sup>[[3]](https://github.com/hukkin/tomli/blob/1bd3345f97cba795d7e6075956815c0a52151ed0/src/tomli/_parser.py#L74)</sup> leaving the extra return. When encountering this, the following exception will be raised: `TOMLDecodeError: Expected newline or end of document after a statement (at line 12, column 44)`.

This issue causes the following commands to prematurely exit on Windows when any plugins are installed: `self lock`, `self show`, `self update` and `self show plugins`.

### Increasing Lines at End of File
tomlkit also persists the number of blank lines after an entry, as a result when preserved tables are present, the newline added by `Factory.create_pyproject_from_package`<sup>[[4]](https://github.com/python-poetry/poetry/blob/71b3d6e030c879f0b4b8e3a08eac2b38a402b6bd/src/poetry/factory.py#L293)</sup> is unnecessary and will cause a new line to be added to the file every time the function is called.

# Changes To Fix The Issues

1. Replace `\r\n` with `\n` before calling `self.system_pyproject.write_text`.
2. Remove the final linebreak if the file ends with `\n\n`.

# Pull Request Check List

- [x] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

2023-03-22 23:12 UTC, dimbleby commented
Something like
```patch
-        self.system_pyproject.write_text(content.as_string(), encoding="utf-8")
+        pyproject = PyProjectTOML(self.system_pyproject)
+        pyproject.file.write(content)
```
should be cleaner, let tomlkit worry about the line endings.  (Which it does, see https://github.com/sdispater/tomlkit/blob/18a527758bfa3f8fe65e2f45f61df42f2f5af0c1/tomlkit/toml_file.py#L47)

per the pipeline, `write_text()` doesn't get the `newline` parameter until python 3.10.

2023-03-23 01:37 UTC, NimajnebEC commented
Thanks for the help! That is definitely a cleaner solution. It's just a case of finding a nice solution to prevent those newlines from being added with this new method.

2023-03-23 07:42 UTC, dimbleby commented
well, one thing at a time.  Although the extra lines and the faulty carriage returns are in the same general area they're really quite different; and one oughtn't cause us to make a worse fix to the other.

re the unwanted newlines: do we _ever_ want that newline?  perhaps just delete the line of code that adds it altogether.  Or, make it caller responsibility to add it if they want it.

2023-03-24 09:48 UTC, NimajnebEC commented
The newline appears to be added solely for code styling, so I'd say it is probably alright to remove. Aside from here, the `Factory.create_pyproject_from_package` method is only used in [`test_factory.py`](https://github.com/python-poetry/poetry/blob/fa5543a639e76d14e7262572ea6b06fe099c0f46/tests/test_factory.py#L152) and [`test_remove_plugins.py`](https://github.com/python-poetry/poetry/blob/fa5543a639e76d14e7262572ea6b06fe099c0f46/tests/console/commands/self/test_remove_plugins.py#L38), neither of which look like they will be effected by the removal of this newline.

2023-03-24 14:29 UTC, radoering requested changes
I'd propose to rename the test file to `test_self_command.py`. Usually, we use the same name as the module we are testing.

2023-03-24 14:29 UTC, radoering commented on tests/console/commands/self/test_system_pyproject.py
> +def test_generate_system_pyproject_carraige_returns(
```suggestion
def test_generate_system_pyproject_carriage_returns(
```

2023-03-26 13:30 UTC, dimbleby commented
fixes #6457, presumably

2023-03-26 14:28 UTC, NimajnebEC commented on src/poetry/factory.py
>              path.joinpath("pyproject.toml").write_text(
Indeed, if any of the used properties contain Windows line endings then the issue will occur here too. So yeah, it is probably best to remove that parameter.

2023-03-27 15:03 UTC, merged