fix: disable wheel content validation
python-poetry/poetry pull request #7987
Opened 2023-05-23 06:31 UTC by ralbertazzi

# Pull Request Check List

Related to: https://github.com/python-poetry/poetry/issues/7983

A temporary solution to https://github.com/python-poetry/poetry/issues/7983 until https://github.com/pypa/installer/pull/183 gets released.

2023-05-23 07:49 UTC, ralbertazzi commented
I added another commit where I achieve what I was saying here: https://github.com/python-poetry/poetry/issues/7983#issuecomment-1558645745

This:
- Requires no release of pypa/installer
- Makes the installation process faster, as we compute file hashes just once
- Does not lose any validation capabilities. They are just handled a bit later

Cons: some pypa/installer code spilling into the Poetry codebase

2023-05-23 15:39 UTC, radoering commented
Not sure if the second commit is worth it or if we should just turn off validation until there is a solution in `installer` (or we really need validation for some reason). For a patch release I'd probably go with the first commit only (and include the second commit in the next minor if we want to include it).

> First commit is a temporary solution to https://github.com/python-poetry/poetry/issues/7983 until https://github.com/pypa/installer/pull/183 gets released.

The installer PR only reduces the memory consumption, the hash will still be computed twice, won't it?

2023-05-26 14:36 UTC, radoering requested changes

2023-05-26 14:36 UTC, radoering commented on src/poetry/installation/wheel_installer.py
> +            )
This doesn't always work. I tested a large project and got a `StopIteration` for some packages.

You can reproduce it by running `poetry add fonttools` for example.

What's even worth: The package is installed, but the `RECORD` file is not written.

`poetry run pip uninstall fonttools` now throws `ERROR: Cannot uninstall fonttools 4.39.4, RECORD file not found. Hint: The package was installed by Poetry 1.6.0.dev0.` and `poetry run pip install fonttools` gives `Requirement already satisfied`.

You can only "manually" uninstall the package.

2023-05-26 14:36 UTC, radoering commented on src/poetry/installation/wheel_installer.py
> +        return super().finalize_installation(scheme, record_file_path, records)
```suggestion
        try:
            self._validate_hash_and_size(records)
        finally:
            return super().finalize_installation(scheme, record_file_path, records)
```

I wonder if we should do something like that to make sure the `RECORD` file is written despite of bugs in `_validate_hash_and_size()`. However, when I tried this, the exception was swallowed, which not good either. Thus, we would have to put more effort here...

2023-05-26 17:02 UTC, ralbertazzi commented
@radoering yes, I agree the PR still needs some touches. The way I got it is that we wouldn't have merged the additional work on top of the simple `validate_contents=False`, am I right?

2023-05-26 18:20 UTC, radoering commented
Yes, I think for 1.5.1 the first commit is fine. The second commit needs more work and testing. You can split the second commit into a separate PR if you want to keep working on it.

2023-05-29 08:30 UTC, radoering approved these changes

2023-05-29 08:35 UTC, merged