feat: perform a single hash validation of wheel files
python-poetry/poetry pull request #8027
Opened 2023-05-28 16:55 UTC by ralbertazzi

Re-introduce wheel content file validation in a more performant way, aka computing (and validating) hash _once_ while installing the wheel (and verifying the wheel at the end of the installation process).

Related to #7983 and #7987

- [ ] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.
- [ ] Address https://github.com/python-poetry/poetry/pull/7987 comments

2023-05-28 17:38 UTC, dimbleby commented
I do not like the amount of pypa/installer that is being duplicated by poetry already, and this isn't helping!

Are you sure you wouldn't prefer to fix up your MR in that project - I see that the pipeline is currently failing - and wait for it to be released?  Then just _use_ pypa/installer instead of re-implementing it?

2023-05-29 08:27 UTC, radoering requested changes
I have copied my comments from the other PR so they will not be forgotten.

I agree that we should prefer a solution in installer if possible. Another approach to avoid calculating the hashes twice might be to add a "use hashes from `RECORD` file" parameter to the `install()` function that can be set if validation was successful.

By the way, what's the performance penalty for calculating the hashes twice for a big wheel like torch?

2023-05-29 08:27 UTC, radoering commented on src/poetry/installation/wheel_installer.py
> +            )
This doesn't always work. I tested a large project and got a `StopIteration` for some packages.

You can reproduce it by running `poetry add fonttools` for example.

What's even worth: The package is installed, but the `RECORD` file is not written.

`poetry run pip uninstall fonttools` now throws `ERROR: Cannot uninstall fonttools 4.39.4, RECORD file not found. Hint: The package was installed by Poetry 1.6.0.dev0.` and `poetry run pip install fonttools` gives `Requirement already satisfied`.

You can only "manually" uninstall the package.

2023-05-29 08:27 UTC, radoering commented on src/poetry/installation/wheel_installer.py
> +        return super().finalize_installation(scheme, record_file_path, records)
```suggestion
        try:
            self._validate_hash_and_size(records)
        finally:
            return super().finalize_installation(scheme, record_file_path, records)
```

I wonder if we should do something like that to make sure the `RECORD` file is written despite of bugs in `_validate_hash_and_size()`. However, when I tried this, the exception was swallowed, which not good either. Thus, we would have to put more effort here...

2023-05-30 07:37 UTC, closed without merging