🧹 clean `poetry.vcs.git.system` module
python-poetry/poetry pull request #8401
Opened 2023-09-04 14:48 UTC by tzing

Clean up duplicated logic in `poetry.vcs.git.system` module and add test for it.

### Pull Request Check List

Relates-to: #3155

- [x] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

2023-09-09 12:19 UTC, radoering requested changes
The `clone` test takes quite long. It might make sense to create a new temporary repo instead of using the poetry repo? (I could imagine it may be faster to clone a repo with only some commits.)

Btw, I think we should name the test file `test_system.py` according to the module we are testing. It's in the git folder anyway.

2023-09-09 12:19 UTC, radoering commented on tests/vcs/git/test_git_system.py
> +        ],
```suggestion
            "--no-gpg-sign",  # avoid user interaction in case signing is turned on
        ],
```

2023-09-11 02:05 UTC, tzing commented
> The clone test takes quite long. It might make sense to create a new temporary repo instead of using the poetry repo?

Okay I can try.

Convert to draft and will work on it later.

2023-09-17 11:44 UTC, radoering approved these changes

2023-09-17 11:45 UTC, merged