Fix POETRY_REPOSITORIES_ variable
python-poetry/poetry pull request #8492
Opened 2023-09-29 14:31 UTC by SamambaMan

POETRY_REPOSITORIES_<NAME>_URL wrong in the documentation

# Pull Request Check List

Resolves: #8491

No changes are required to the code.

2023-09-29 15:10 UTC, dimbleby commented
it's not so simple as that: `POETRY_REPOSITORIES_<NAME>_URL` is specifically for setting the url associated with a repository ie it corresponds to `repositories.<name>.url`.

I can believe that there are clarity improvements to be made here and it would be good to see that: but I don't think this MR as it stands helps with that

2023-09-29 15:28 UTC, SamambaMan commented
What do you suggest?
I merely wrote the same as it in the code (i think) for doing as the manual won't work.

Do you want me to explain that the <name> should match naming in sources?

2023-09-29 15:38 UTC, dimbleby commented
the current doc has a heading `repositories.name`.  You are reporting - I think rightly - that as an environment variable this isn't very useful because you never want to configure only a repository name: you want to configure sub-properties of the repository (in particular, the URL).

However your MR leaves that heading alone, so now the doc is not self-consistent.

I realise that disentangling this is more than the four character fix you were hoping for!

2023-09-29 15:54 UTC, SamambaMan commented
Oh, i get it now.
This should cover other parameters as priority as well, right?
I'm hovering the code and this is not supported code wise yet also, right?

2023-09-29 16:46 UTC, dimbleby commented
As I understand it, global repository configuration is only interesting during publishing, so eg priority is irrelevant - I think url is the only interesting property.

2023-09-29 17:27 UTC, SamambaMan commented
So...? :D

2023-09-29 18:49 UTC, dimbleby commented
So: put some or more of that in the docs!

2023-10-03 20:25 UTC, SamambaMan commented
@dimbleby check if this is better.
Also included fixes for basic auth as tested in https://github.com/python-poetry/poetry/blob/47a3a19c442c21aa5b2836ea092dda8ae4d13151/tests/utils/test_authenticator.py#L355

2023-10-11 13:39 UTC, SamambaMan commented
Can I improve this PR in any way?
Let me know

2023-10-13 15:12 UTC, radoering requested changes

2023-10-13 15:12 UTC, radoering commented on docs/configuration.md
> +Set a new alternative repository URL for `name` repository
```suggestion
Set the repository URL for `<name>`.
```

2023-10-13 15:12 UTC, radoering commented on docs/configuration.md
> +See [Repositories]({{< relref "repositories" >}}) for more information.
```suggestion
See [Publishable Repositories]({{< relref "repositories#publishable-repositories" >}}) for more information.
```

2023-10-25 04:50 UTC, radoering approved these changes

2023-10-25 04:51 UTC, merged