draft: use poetry native dep management for PEP517
python-poetry/poetry pull request #9168
Opened 2024-03-17 03:06 UTC by abn

2024-03-17 14:22 UTC, Secrus requested changes
SOme initial points

2024-03-17 15:20 UTC, radoering commented on src/poetry/utils/pep517_build.py
My first thought was the same. (We could put it under `installation`.) However, it's also used for `inspection` where the built wheels will never be installed so I don't think that's a good place.

I still think the best place (except for `utils` 😉) might be `masonry` although that's currently more for Poetry project builders.

Re naming of the module: `isolated_build`?

2024-03-17 20:08 UTC, abn commented on src/poetry/utils/pep517_build.py
> +            Locker(self._env.path.joinpath("poetry.lock"), {}),
This is existing code moved. We can improve that in another PR, right now I am trying to keep the existing code as best as I can.

2024-03-17 21:10 UTC, abn commented on src/poetry/utils/pep517_build.py
I have made the changes to the names, but left it in utils for now - its an easy enough change for later to move i i reckon. Right now, I feel utils is the best place for it as it is not used for a single purpose.

2024-03-17 21:11 UTC, abn commented on src/poetry/inspection/info.py
>              logger.debug("PEP517 build failed: %s", e)
Yeah. let's do that in another PR.

2024-03-17 21:12 UTC, abn commented
@Secrus let me know if functionally anything needs to change. If not, I can tidy the commit up and make the PR ready once #9132 is merged - it should have an impact on the test cases.

2024-03-17 21:54 UTC, Secrus commented
I guess it's a replacement for #5650?

2024-03-17 21:58 UTC, abn commented
> I guess it's a replacement for #5650?

Oh hey, past me had the same idea. Few things I might actually borrow from that one. Thanks for pointing that out.

2024-03-19 14:02 UTC, Secrus commented
@abn did you maybe check the performance of this? In your previous attempt at #5650 you mentioned [there was some performance regression](https://github.com/python-poetry/poetry/pull/5650#issuecomment-1134579741)

2024-03-19 14:06 UTC, abn commented
It does still incur the solving penalty. But overall the test suite is faster by a little bit for the following reason. 

1. We now use bare venvs. And a lot around this has improved since the old PR. 
2. We remove a couple of subprocess calls. 
3. From the test suite we also removed the pip freeze call that dropped 2 seconds from that test as well. 

Overall I think this improves our posture. The next step for this would be to optimize cached build environments or removing the solver penalty. We can basically allow for the latest matching versions to be installed fairly confidently.

2024-03-19 14:09 UTC, Secrus commented
The test suite is one thing, but did you check what the actual perf regression is? Is it within ~10% or more?

2024-03-19 14:13 UTC, Secrus commented
The reason I am asking is that I would like us to know how serious we should be about improving the performace. Should that be next PR, but before next version release or can it be something down the line because the ecosystem is now in a better place and this path won't be hit that often?

2024-03-19 14:18 UTC, abn commented
The test suite is a good indicator for any major hits. 

Since we do not really have empirical data for the old build mechanism, we will have to try doing some experiments. I'll see what I can do. 

Finger in the air, I'd say for majority cases (simple/common build require combinations) we would be quicker than subprocess pip install. And for the other cases, it will depend on the build requires constraints. 

This change also brings with it some additional benefits that offset performance impact. 

1. Cache reuse. 
2. Repository configuration reuse.

2024-03-19 14:54 UTC, abn commented
> Since we do not really have empirical data for the old build mechanism, we will have to try doing some experiments. I'll see what I can do.

Did a quick hacky evaluation using the following snippet.

```python
from pathlib import Path

from poetry.inspection.info import get_pep517_metadata

if __name__ == '__main__':
    _ = get_pep517_metadata(Path("tests/fixtures/project_with_setup"))
```

I ran this script 100 times and timed it.

**Poetry 1.8.2**
```
real	0m11.508s
user	0m9.374s
sys	0m2.078s
```

**PR 9168**
```
real    0m13.500s
user    0m11.031s
sys     0m2.388s
```

On average the performance hit is 0.02 seconds per run.

2024-03-19 16:30 UTC, radoering commented
> Finger in the air, I'd say for majority cases (simple/common build require combinations) we would be quicker than subprocess pip install. And for the other cases, it will depend on the build requires constraints.

Our nemesis of build requirements is probably `oldest-supported-numpy`. However, I suppose most packages that depend on that provide wheels. Thus, it might not be that relevant. A potential solver optimization would be to just solve for the current environment instead of solving cross-platform (only for isolated build environments) but I haven't looked into it in detail because I did not see any reports where this is a bottleneck.

In a quick real-world test, I could not observe a regression either.

2024-03-19 16:31 UTC, radoering approved these changes

2024-03-19 17:41 UTC, merged

2024-03-19 18:38 UTC, dimbleby commented
@abn merging this into the "remove the setup reader" pull request causes quite a lot of test failures with stacks ending like
```
/home/dch/poetry/src/poetry/repositories/cached_repository.py:50: in get_release_info                                              return PackageInfo.load(self._get_release_info(name, version))                                                             /home/dch/poetry/src/poetry/repositories/legacy_repository.py:114: in _get_release_info
    return self._links_to_data(                                                                                                /home/dch/poetry/src/poetry/repositories/http_repository.py:365: in _links_to_data
    info = self._get_info_from_links(links, ignore_yanked=not data.yanked)
/home/dch/poetry/src/poetry/repositories/http_repository.py:328: in _get_info_from_links                                           return self._get_info_from_metadata(sdists[0]) or self._get_info_from_sdist(
/home/dch/poetry/src/poetry/repositories/http_repository.py:160: in _get_info_from_sdist
    return PackageInfo.from_sdist(filepath)
/home/dch/poetry/src/poetry/inspection/info.py:473: in from_sdist
    return cls._from_sdist_file(path=path)
/home/dch/poetry/src/poetry/inspection/info.py:329: in _from_sdist_file
    new_info = cls.from_directory(path=sdist_dir)
/home/dch/poetry/src/poetry/inspection/info.py:453: in from_directory
    info = get_pep517_metadata(path)
/home/dch/poetry/src/poetry/inspection/info.py:534: in get_pep517_metadata
    with isolated_builder(path, "wheel") as builder:
/usr/lib/python3.10/contextlib.py:135: in __enter__
    return next(self.gen)
/home/dch/poetry/src/poetry/utils/isolated_build.py:121: in isolated_builder
    pool = pool or Factory().create_poetry().pool
/home/dch/poetry/src/poetry/factory.py:57: in create_poetry
    base_poetry = super().create_poetry(cwd=cwd, with_groups=with_groups)
/home/dch/poetry-core/src/poetry/core/factory.py:49: in create_poetry
    poetry_file = self.locate(cwd)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cls = <class 'poetry.factory.Factory'>
cwd = PosixPath('/tmp/pytest-of-dch/pytest-2/popen-gw0/test_solver_chooses_from_secon0')

    @classmethod
    def locate(cls, cwd: Path | None = None) -> Path:
        cwd = Path(cwd or Path.cwd())
        candidates = [cwd]
        candidates.extend(cwd.parents)

        for path in candidates:
            poetry_file = path / "pyproject.toml"
                return poetry_file

        else:
>           raise RuntimeError(
                f"Poetry could not find a pyproject.toml file in {cwd} or its parents"
            )
E           RuntimeError: Poetry could not find a pyproject.toml file in /tmp/pytest-of-dch/pytest-2/popen-gw0/test_solver_choo
ses_from_secon0 or its parents
```
have not yet dug into this but suspect a bug in this one?

will make similar comment in that MR for visibility, apologies if you see both!

2024-03-19 18:48 UTC, abn commented
@dimbleby the build is expected to run within a project context. You can add something like this to the suite. 

```
@pytest.fixture(autouse=True) 
 def use_project_context(set_project_context: SetProjectContext) -> Iterator[None]: 
     with set_project_context("sample_project"): 
         yield
```

Alternatively, if the assumption that the isolated builder is only ever setup within a project context is wrong we might need to handle this in the isolated builder context.

2024-03-19 19:04 UTC, dimbleby commented
oh awkward.  we probably ought to have been passing the `poetry` object along the call path all the way, this is getting a little bit spooky-action-at-a-distance.  But I see that is quite far from convenient...

2024-03-19 19:18 UTC, abn commented
Yeah, ideally it would have been nice to have the poetry instance during inspection too, but that would require some additional work I reckon.

For now, I have raised #9180 to soften the issue.