[1.8 backport] inspection: error on unsupported metadata versions
python-poetry/poetry pull request #9229
Opened 2024-03-24 17:23 UTC by neersighted

Backport #9203 to 1.8.

---

Resolves: https://github.com/python-poetry/poetry/issues/9195

This change also handles a previously unidentified bug. Previously, when processing wheel files, `PackageInfo` incorrectly
returned an empty instance. This change ensures a `PackageInfoError` is correctly raised. See 36bf3251f548d27a81677be32a87013a4b41f101.

2024-03-24 17:27 UTC, neersighted commented
Note that this is without the test as it did not apply cleanly; let me know if you want me to try to bring it forward as well.

2024-03-24 18:00 UTC, abn approved these changes

2024-03-28 16:31 UTC, jfly requested changes
I don't see the `if dist.metadata_version not in pkginfo.distribution.HEADER_ATTRS` check that's a key piece of https://github.com/python-poetry/poetry/pull/9203/. Is that intentionally omitted here?

2024-04-12 15:13 UTC, jfly approved these changes
I haven't manually tested this version with my [test harness](https://github.com/jfly/2024-03-19-poetry-build-deps-issue), but the code LGTM!

2024-04-12 15:13 UTC, jfly commented on src/poetry/inspection/info.py
> +            raise ValueError("Unknown metadata version")
nit: consider including the version number here as in https://github.com/python-poetry/poetry/pull/9226

2024-04-22 16:03 UTC, radoering approved these changes

2024-04-22 16:03 UTC, merged