`--no-truncate` flag in show command
python-poetry/poetry pull request #9580
Opened 2024-07-25 15:27 UTC by ch1nq

In order to get a more consistent output from the `poetry show` command, this PR introduces a `--no-truncate` flag to the command. When the flag is set the show command does not take the width of the terminal into account when deciding the level of detail to print.

# Pull Request Check List

- [x] Added **tests** for changed code.
- [x] Updated **documentation** for changed code.

2025-01-17 20:34 UTC, abn reviewed
Why not just set `width = math.inf if self.option("--no-truncate") else ...`? simplifies the code changes a lot.

2025-01-17 20:34 UTC, abn commented
Also, you might need to re-do the cli doc changes, since we reodered that doc.

2025-02-06 10:42 UTC, ch1nq commented
> @ch1nq is this something you'd like to continue working on?

Thanks for the review - I will apply the suggested changes

2025-02-07 09:16 UTC, ch1nq commented
@abn I have gone with `sys.maxsize` instead of `math.inf`, since we need it to be an int. This is because we use the value as a slice index later in the code.

2025-02-07 18:49 UTC, abn requested changes

2025-02-07 18:49 UTC, abn commented on docs/cli.md
> +* `--no-truncate`: Do not truncate the output based on the terminal width.
I think this is in the wrong place.

2025-02-10 09:05 UTC, ch1nq commented on docs/cli.md
> +* `--no-truncate`: Do not truncate the output based on the terminal width.
Good catch! Must have been moved when I merged in `main`

2025-02-11 22:16 UTC, abn submitted a review, later dismissed

2025-02-12 11:47 UTC, radoering approved these changes

2025-02-12 11:52 UTC, merged