feat(install): add `--all-groups` flag to install all dependency groups
python-poetry/poetry pull request #9744
Opened 2024-10-09 09:46 UTC by schneebuzz

This PR adds the `--all-groups` flag to `poetry install` which includes all the dependency groups (including optional groups) for installation. This is a very common use case for projects with multiple optional groups and allows the user to *install everything* without specifying each group.

This feature has been discussed in the past. See e.g. #7605 and #5461. I gave it another shot with an implementation that respects the existing options and flags.

I decided not to go with `--with=all` or similar and instead use the explicit flag `--all-groups`, consistent with the `--all-extras` flag. A naming alternative would be `--with-all`.

Options like
- `--all-groups --without=docs` are supported,
- `--all-groups --with=foo` ignores the `with` with a warning, 
- and `--all-groups --only=foo` results in an error.

# Pull Request Check List

- [x] Added **tests** for changed code.
- [x] Updated **documentation** for changed code.

2024-10-10 05:42 UTC, schneebuzz commented
Please review, feedback welcome.

2024-10-10 08:57 UTC, Secrus approved these changes
LGTM. @radoering, care to take a look?

2024-10-10 17:41 UTC, radoering commented
I will take a look tomorrow.

2024-10-11 13:48 UTC, radoering reviewed
LGTM. There is just one thing: https://github.com/python-poetry/poetry-plugin-export/pull/294 introduces `--all-groups` to `poetry export` (not yet released). It is the same name; that is good. However, in `poetry export` `--all-groups` conflicts with `--with` and `--without`. I have no clear preference, but we should make it consistent.

2024-10-13 12:16 UTC, schneebuzz commented
> LGTM. There is just one thing: [python-poetry/poetry-plugin-export#294](https://github.com/python-poetry/poetry-plugin-export/pull/294) introduces `--all-groups` to `poetry export` (not yet released). It is the same name; that is good. However, in `poetry export` `--all-groups` conflicts with `--with` and `--without`. I have no clear preference, but we should make it consistent.

Thanks for reviewing.
Even though the *all but without* could be handy, I aligned with the referenced PR since it leaves less room for confusion.

2024-10-15 04:39 UTC, radoering requested changes

2024-10-15 04:39 UTC, radoering commented on docs/cli.md
> +When `--all-groups` is specified, the `--with` option is ignored.
That is not up to date anymore.

2024-10-15 06:07 UTC, schneebuzz commented on docs/cli.md
> +When `--all-groups` is specified, the `--with` option is ignored.
Apologies for missing that one. Fixed.

2024-10-15 15:21 UTC, radoering approved these changes

2024-10-15 15:22 UTC, merged